- name: Create project dir
  file:
    path: "{{ project_path }}"
    state: directory

- name: Clone repo
  git:
    # repo: "https://github.com/innovity-Technologies-Inc/cgw_cicd.git"
    repo: "https://github.com/laravel/laravel"
    dest: "{{ project_path }}"
    version: master 
    force: yes
    accept_hostkey: yes
    depth: 1

- name: Install dependencies
  command: composer install
  args:
    chdir: "{{ project_path }}"

- name: Copy env
  template:
    src: env.j2
    dest: "{{ project_path }}/.env"

- name: Generate key
  command: php artisan key:generate
  args:
    chdir: "{{ project_path }}"

- name: Run migrations
  command: php artisan migrate --force
  args:
    chdir: "{{ project_path }}"
