- name: Update system
  apt:
    update_cache: yes

- name: Install base tools
  apt:
    name:
      - curl
      - git
      - unzip
      - wget
      - software-properties-common
    state: present
